### ISSUE TITLE
How to modify the code to call both Print and Say (ie. write and speak in unison)?

### ISSUE THREAD

**Issue by forthrin** [flori/ollama-ruby#1]
```ruby
ollama.chat(model: 'llama3.1', stream: true, messages:, &Print)
```

**Comment by flori** [comment]
The lambda version of it would be

```ruby
messages = { role: 'user', content: 'Why is the sky blue (no markdown)?' }
say = Say.new
print_say = -> r { Print.(r); say.(r) }
ollama.chat(model: 'llama3.1', stream: true, messages:, &print_say)
```

A more elaborate example that includes the `Handlers::Concern` is the `FollowChat` class in the  `ollama_chat` executable: https://github.com/flori/ollama-ruby/blob/master/bin/ollama_chat#L110

**Comment by forthrin** [comment]
Thanks! Though Print is blocking before Say gets a chance. I assume syncing them is not trivial, as Say needs the text to be generated (JiT) before it can speak it, and the words are generated at their own pace. Does the software offer this combination in any form or what is this ETA way into the future?

**Comment by flori** [comment]
There seems to be an interactive mode in the macos say command, that marks the words that are currently spoken in a sentence. It can now be enabled by passing `interactive: true` like this https://github.com/flori/ollama-ruby/blob/master/spec/ollama/handlers/say_spec.rb#L28 for reverse video and this for arbitrary colors or terminfo capabilities by passing a string like https://github.com/flori/ollama-ruby/blob/master/spec/ollama/handlers/say_spec.rb#L41 in the Say handler.

**Comment by forthrin** [comment]
Bit confused here... Does Ollama use the macOS `say` command to speak...?

(Is the Ollama `Say` class analogous with the macOS `say` command?)

Thought it had its own speech engine, with no relation to the (legacy, but maybe due for a comeback) macOS `say`.

**Comment by flori** [comment]
This library interacts with a local ollama server, that provides access to various LLMs via its API running them on llama.cpp returning the output, which is text. The `Say` handler can be used to speak the returned text.
